# Site settings
title: 'Darkest Hour' # Your Title
tagline: 'Twisted tales to make you shudder' # A brief tagline for your site
sidebar_image: /images/cover_1.jpg

# Build settings
#markdown: redcarpet
#highlighter: pygments
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
css_class: 'highlight'

baseurl: /darkesthour # the subpath of your site, e.g. /blog/
